# Generated by Django 5.2.3 on 2025-10-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CHSModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom et prénom')),
                ('quartier', models.CharField(max_length=255, verbose_name='Quartier')),
                ('commune', models.CharField(max_length=255, verbose_name='Commune')),
                ('nni', models.CharField(blank=True, max_length=50, verbose_name='NNI')),
                ('age', models.IntegerField(verbose_name='Âge')),
                ('role', models.CharField(choices=[('chef_homme', 'Chef de ménage (Homme)'), ('chef_femme', 'Chef de ménage (Femme)'), ('membre', 'Membre'), ('autre', 'Autre')], max_length=20, verbose_name='Statut dans le ménage')),
                ('cohab', models.CharField(choices=[('famille_parente', 'Avec parenté directe'), ('famille_non_parente', 'Sans parenté directe'), ('seul_errant', 'Seul / errant')], max_length=20, verbose_name='Situation de cohabitation')),
                ('tel', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], max_length=3, verbose_name='Téléphone portable')),
                ('enf05', models.IntegerField(default=0, verbose_name="Nb. d'enfants 0-5 ans")),
                ('orphelins', models.IntegerField(default=0, verbose_name="Nb. d'enfants orphelins")),
                ('charge', models.IntegerField(default=0, verbose_name='Autres personnes à charge')),
                ('hab_type', models.CharField(choices=[('tente', 'Tente'), ('hangar', 'Hangar'), ('baraque', 'Baraque'), ('banco', 'Maison en banco'), ('zinc', 'Maison en zinc'), ('beton', 'Maison en béton armé')], max_length=20, verbose_name="Type d'habitat")),
                ('pieces', models.CharField(choices=[('1_2', '1-2'), ('3_4', '3-4'), ('5p', '5 et +')], max_length=10, verbose_name='Nombre de pièces')),
                ('propriete', models.CharField(choices=[('prete', 'Prêté'), ('location', 'Location'), ('proprietaire', 'Propriétaire')], max_length=20, verbose_name='Statut de propriété')),
                ('eclairage', models.CharField(choices=[('bougie', 'Bougie / Lampe / Torche'), ('electricite', 'Électricité')], max_length=20, verbose_name='Éclairage')),
                ('eau', models.CharField(choices=[('adduction', "Adduction d'eau"), ('reserve', "Réserve d'eau"), ('charrette', 'Charrettes'), ('puits', 'Puits')], max_length=20, verbose_name='Approvisionnement en eau')),
                ('latrine', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], max_length=3, verbose_name='Latrines')),
                ('emploi', models.CharField(choices=[('emploi', 'Ayant un emploi'), ('sans_emploi', 'Sans emploi')], max_length=20, verbose_name='Situation')),
                ('nature_emploi', models.CharField(blank=True, choices=[('fixe', 'Fixe'), ('temporaire', 'Temporaire'), ('saisonnier', 'Saisonnier')], max_length=20, verbose_name="Nature de l'emploi")),
                ('revenu_mensuel', models.CharField(blank=True, choices=[('moins_25000', '< 25 000 UM'), ('25k_30k', '25 000-30 000 UM'), ('plus_31k', '>= 31 000 UM')], max_length=20, verbose_name='Montant mensuel')),
                ('raison_chomage', models.CharField(blank=True, choices=[('incapacite', 'Incapacité à travailler'), ('chomage', 'Chômage')], max_length=20, verbose_name='Motif')),
                ('soutien', models.CharField(choices=[('proche', 'Proche parent'), ('autres', 'Voisins / autres')], max_length=20, verbose_name='Principal soutien de la famille')),
                ('foncier', models.CharField(choices=[('commercial', 'Commercial'), ('agricole', 'Agricole'), ('habitation', 'Pour habitation'), ('neant', 'Néant')], max_length=20, verbose_name='Type')),
                ('camelins', models.IntegerField(default=0, verbose_name='Chameaux')),
                ('bovins', models.IntegerField(default=0, verbose_name='Bovins')),
                ('ovins', models.IntegerField(default=0, verbose_name='Ovins/Caprins')),
                ('malades', models.IntegerField(default=0, verbose_name='Malades de longue durée')),
                ('handicapes', models.IntegerField(default=0, verbose_name='Personnes handicapées')),
                ('poly', models.IntegerField(default=0, verbose_name='Polyhandicapés')),
                ('score', models.IntegerField(default=0, verbose_name='Score total')),
                ('decision', models.CharField(default='Non indigent', max_length=50, verbose_name='Décision')),
                ('num_dossier', models.CharField(max_length=50, unique=True, verbose_name='Numéro de dossier')),
                ('date_jour', models.DateField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Modèle CHS',
                'verbose_name_plural': 'Modèles CHS',
            },
        ),
    ]
