# Generated by Django 5.2.3 on 2025-10-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHS_Modele_off', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chsmodel',
            old_name='charge',
            new_name='personne_a_charge',
        ),
        migrations.RenameField(
            model_name='chsmodel',
            old_name='cohab',
            new_name='situation_de_vie',
        ),
        migrations.RemoveField(
            model_name='chsmodel',
            name='emploi',
        ),
        migrations.RemoveField(
            model_name='chsmodel',
            name='enf05',
        ),
        migrations.RemoveField(
            model_name='chsmodel',
            name='nature_emploi',
        ),
        migrations.RemoveField(
            model_name='chsmodel',
            name='orphelins',
        ),
        migrations.RemoveField(
            model_name='chsmodel',
            name='raison_chomage',
        ),
        migrations.RemoveField(
            model_name='chsmodel',
            name='revenu_mensuel',
        ),
        migrations.AddField(
            model_name='chsmodel',
            name='Orphelins_dans_le_ménage',
            field=models.IntegerField(default=0, verbose_name='Orphelin(s)'),
        ),
        migrations.AddField(
            model_name='chsmodel',
            name='sexe',
            field=models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme')], default='homme', max_length=10, verbose_name='Sexe'),
        ),
        migrations.AddField(
            model_name='chsmodel',
            name='situation_matrimoniale',
            field=models.CharField(choices=[('marie', 'Marié(e)'), ('celibataire', 'Celibataire'), ('veuf_veuve', 'Veuf/Veuve'), ('divorce_separe', 'Divorcé/Separé')], default='celibataire', max_length=20, verbose_name='Situation matrimoniale'),
        ),
        migrations.AddField(
            model_name='chsmodel',
            name='statut_prof',
            field=models.CharField(choices=[('emploie fixe', 'Emploi fixe'), ('Emploi partiel', 'Emploi partiel'), ('Emploi saisonnier', 'Emploi saisonnier'), ('sans Emploi (chomage)', ' sans Emploi (chomage)'), ('sans Emploi (incapacité à travailler)', ' sans Emploi (incapacité à travailler) ')], default='sans Emploi (incapacité à travailler)', max_length=50, verbose_name='Statut professionnel'),
        ),
        migrations.AlterField(
            model_name='chsmodel',
            name='role',
            field=models.CharField(choices=[('chef', 'Chef de ménage'), ('membre', 'Membre'), ('autre', 'Autre')], max_length=20, verbose_name='Statut dans le ménage'),
        ),
        migrations.AddField(
            model_name='chsmodel',
            name='Revenu_mensuel',
            field=models.CharField(blank=True, max_length=50, verbose_name='Revenu mensuel'),
        ),
    ]
