# Generated by Django 5.2.3 on 2025-10-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHS_Modele_off', '0002_rename_charge_chsmodel_personne_a_charge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chsmodel',
            name='Revenu_mensuel',
        ),
        migrations.RemoveField(
            model_name='chsmodel',
            name='statut_prof',
        ),
        migrations.AddField(
            model_name='chsmodel',
            name='emploi',
            field=models.CharField(choices=[('emploi', 'Ayant un emploi'), ('sans_emploi', 'Sans emploi')], default='sans_emploi', max_length=20, verbose_name='Situation'),
        ),
        migrations.AddField(
            model_name='chsmodel',
            name='enf05',
            field=models.IntegerField(default=0, verbose_name='Enfants 0-5 ans'),
        ),
        migrations.AddField(
            model_name='chsmodel',
            name='nature_emploi',
            field=models.CharField(blank=True, choices=[('fixe', 'Fixe'), ('temporaire', 'Temporaire'), ('saisonnier', 'Saisonnier')], max_length=20, verbose_name="Nature de l'emploi"),
        ),
        migrations.AddField(
            model_name='chsmodel',
            name='raison_chomage',
            field=models.CharField(blank=True, choices=[('incapacite', 'Incapacité à travailler'), ('chomage', 'Chômage')], max_length=20, verbose_name='Motif'),
        ),
        migrations.AlterField(
            model_name='chsmodel',
            name='role',
            field=models.CharField(choices=[('chef_homme', 'Chef de ménage (Homme)'), ('chef_femme', 'Chef de ménage (Femme)'), ('membre', 'Membre'), ('autre', 'Autre')], max_length=20, verbose_name='Statut dans le ménage'),
        ),
        migrations.AddField(
            model_name='chsmodel',
            name='revenu_mensuel',
            field=models.CharField(blank=True, choices=[('moins_25000', '< 25 000 UM'), ('25k_30k', '25 000–30 000 UM'), ('plus_31k', '>= 31 000 UM')], max_length=20, verbose_name='Montant mensuel'),
        ),
    ]
