# Generated by Django 5.2.3 on 2025-10-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHS_Modele_off', '0003_remove_chsmodel_revenu_mensuel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chsmodel',
            name='role',
            field=models.CharField(choices=[('chef_menage', 'Chef de ménage '), ('membre', 'Membre'), ('autre', 'Autre')], max_length=20, verbose_name='Statut dans le ménage'),
        ),
    ]
