# Generated by Django 5.2.3 on 2025-10-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHS_Modele_off', '0004_alter_chsmodel_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='chsmodel',
            name='moughataa',
            field=models.CharField(blank=True, choices=[('nouakchott', 'Nouakchott'), ('boutilimit', 'Boutilimit'), ('kaedi', 'Kaédi'), ('selibaby', 'Sélibaby'), ('aioun', 'Aioun'), ('atâr', 'Atâr'), ('ouadane', 'Ouadane'), ('chinguetti', 'Chinguetti'), ('oualata', 'Oualata'), ('tidjikja', 'Tidjikja'), ('nema', 'Néma'), ('timbedra', 'Timbedra'), ('kiffa', 'Kiffa'), ('magta_lahjar', 'Magta-Lahjar'), ('boghe', 'Boghé'), ('bababe', 'Bababé'), ('mbagne', 'Mbagne'), ('alekh', 'Aleg'), ('mederdra', 'Mederdra'), ('akjoujt', 'Akjoujt'), ('tevragh_zeina', 'Tevragh-Zeina'), ('rosso', 'Rosso'), ('keur_massene', 'Keur Massène'), ('riyad', 'Riyad'), ('lexeiba', 'Lexeiba'), ('nouadhibou', 'Nouadhibou'), ('adre', 'Adre'), ('monguel', 'Monguel'), ('djiguenni', 'Djiguenni'), ('amakhtiar', 'Amakhtiar'), ('moudjeria', 'Moudjeria'), ('timbedgha', 'Timbedgha'), ('barkeol', 'Barkéol'), ('guerou', 'Guérou'), ('diadjibine_semme', 'Diadjibine-Semmé'), ('oudalan', 'Oudalan'), ('sori_mal', 'Sori-Mal'), ('aghchorguit', 'Aghchorguit'), ('fderik', 'Fderik'), ('bir_moghrein', 'Bir Moghrein'), ('zoueratt', 'Zoueratt'), ('tichitt', 'Tichitt'), ('mbera', 'Mbera'), ('rachid', 'Rachid'), ('oumpouere', 'Oumpouere'), ('jinah', 'Jinah'), ('el_mina', 'El Mina'), ('dar_naim', 'Dar Naïm'), ('toujouonine', 'Toujouonine'), ('kobenni', 'Kobenni'), ('barrage', 'Barrage'), ('sebkha', 'Sebkha')], max_length=50, verbose_name='Moughataa'),
        ),
        migrations.AddField(
            model_name='chsmodel',
            name='revenu_mensuelle',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Revenu mensuelle (UM)'),
        ),
        migrations.AddField(
            model_name='chsmodel',
            name='wilaya',
            field=models.CharField(blank=True, choices=[('adrar', 'Adrar'), ('assaba', 'Assaba'), ('brakna', 'Brakna'), ('dakhlet_nouadhibou', 'Dakhlet Nouadhibou'), ('gorgol', 'Gorgol'), ('guidimaka', 'Guidimaka'), ('hodh_ech_chargui', 'Hodh Ech Chargui'), ('hodh_el_gharbi', 'Hodh El Gharbi'), ('inchiri', 'Inchiri'), ('nouakchott_nord', 'Nouakchott Nord'), ('nouakchott_ouest', 'Nouakchott Ouest'), ('nouakchott_sud', 'Nouakchott Sud'), ('tagant', 'Tagant'), ('tiris_zemmour', 'Tiris Zemmour'), ('trarza', 'Trarza')], max_length=50, verbose_name='Wilaya'),
        ),
    ]
