# Generated by Django 5.2.3 on 2025-10-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHS_Modele_off', '0007_alter_utilisateur_options_alter_utilisateur_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chsmodel',
            name='commune',
        ),
        migrations.AlterField(
            model_name='chsmodel',
            name='revenu_mensuel',
            field=models.CharField(blank=True, choices=[('moins_25000', '< 25 000 UM'), ('25k_30k', '25 000–30 000 UM'), ('plus_31k', '>= 31 000 UM')], default='', max_length=20, verbose_name='Montant mensuel'),
        ),
    ]
